GET http://localhost:8080/users/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RALm5lZWR3ZXIiLCJpZCI6OCwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjQwMzQ4NzcyLCJleHAiOjE2NDAzOTE5NzJ9.YL6IOh6tX9WUoqFcsn7h-GAJjbr4QbkCaK5aAkdxB_A
###

GET http://localhost:8080/users/2
Content-Type: application/json

###

DELETE http://localhost:8080/users/delete/1
Content-Type: application/json

###

POST http://localhost:8080/users/login
Content-Type: application/json

{

"email":"test@.needwer",
"password":"123456"

}

###

POST http://localhost:8080/users/add
Content-Type: application/json

{

"user":{
"name":"Pavel",
"last_name":"Nikitenko",
"phone":"11111111",
"email":"p.nikitenko@leviossa.net",
"isAdmin":true,
"password":"123456",
"image":"test"
}

}

###


