-- AlterTable
ALTER TABLE "Categories" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Defect" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Setups" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
